name: CI
'on':
  push:
    branches:
      - main
  pull_request: null
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
      - name: Install deps (workspace)
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm -r lint
      - name: Build
        run: pnpm -r build
      - name: Test
        run: pnpm -r test -- --passWithNoTests
